# Generated by Django 3.2.8 on 2021-12-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211110_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availableQuantity',
            field=models.DecimalField(decimal_places=0, default=2, max_digits=6),
            preserve_default=False,
        ),
    ]
